### ISSUE TITLE
Update obsolete download addresses

### ISSUE THREAD

**Issue by SetTrend** [pxcbe/apt-installer#2]
Would you mind updating your script to latest version of `apt-get`?

Some of the download addresses in the script don't exist anymore and yield a HTTP 404, e.g.:

http://ftp.de.debian.org/debian/pool/main/g/glibc/libc6_2.31-13+deb11u2_armel.deb

**Comment by Jusufs** [comment]
Please make the above corrections according non existent links.

**Comment by SetTrend** [comment]
I actually did. And I took the opportunity to improve the script a little bit at the same time while I was looking for the new package versions.

I noticed you already found the repository I created for my amendment?
